version: '3.9'

services:
  app:
    build: .
    container_name: telegram_bot_one
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  redis:
    image: redis/redis-stack:latest
    container_name: redisSpting
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsightSpring
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/db

volumes:
  redis_data:
  redisinsight_data:
