spring.application.name=telegram_bot_one

telegram.bot.token=8370141070:AAFYuNgIW8n1vwiTHobhW_QdZzo0eeOiRTo


# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.timeout=5000ms
